from enum import Enum


class Intent(str, Enum):
    REQUEST_BUNDLE = "REQUEST_BUNDLE"
    CREATE_PLAN = "CREATE_PLAN"
    MODIFY_PLAN = "MODIFY_PLAN"
    FLIGHT_SEARCH = "FLIGHT_SEARCH"
    FLIGHT_BOOK = "FLIGHT_BOOK"
    HOTEL_SEARCH = "HOTEL_SEARCH"
    HOTEL_BOOK = "HOTEL_BOOK"
    ESTIMATE_BUDGET = "ESTIMATE_BUDGET"
    MANAGE_BOOKING = "MANAGE_BOOKING"
    OPTIMIZE_ROUTE = "OPTIMIZE_ROUTE"
    RECOMMEND_VENUE = "RECOMMEND_VENUE"
    MANAGE_TRIP = "MANAGE_TRIP"
    USER_PROFILE = "USER_PROFILE"
    TRAVEL_STYLE = "TRAVEL_STYLE"
    TRIP_DIARY = "TRIP_DIARY"
    CANCEL_PLAN = "CANCEL_PLAN"
    EXPORT_PLAN = "EXPORT_PLAN"
    CALCULATE_COST = "CALCULATE_COST"
    RECOMMEND_PLACE = "RECOMMEND_PLACE"
    SUMMARY = "SUMMARY"
