"""Canonical plan evaluation failure types."""

# Hard constraint
MUST_INCLUDE_MISSING = "MUST_INCLUDE_MISSING"
MUST_AVOID_INCLUDED = "MUST_AVOID_INCLUDED"
FINAL_ANCHOR_VIOLATION = "FINAL_ANCHOR_VIOLATION"
ORDERED_ANCHOR_VIOLATION = "ORDERED_ANCHOR_VIOLATION"
DUPLICATE_PLACE = "DUPLICATE_PLACE"
DUPLICATE_DAY_PATTERN = "DUPLICATE_DAY_PATTERN"
LOW_WALKING_VIOLATION = "LOW_WALKING_VIOLATION"

# Soft preference
TIME_SLOT_MISMATCH = "TIME_SLOT_MISMATCH"
PACE_TOO_FAST = "PACE_TOO_FAST"
PACE_TOO_SLOW = "PACE_TOO_SLOW"
MEAL_STYLE_MISMATCH = "MEAL_STYLE_MISMATCH"
TRAVEL_STYLE_MISMATCH = "TRAVEL_STYLE_MISMATCH"
STORY_FLOW_WEAK = "STORY_FLOW_WEAK"
PERSONA_MISMATCH = "PERSONA_MISMATCH"
MUSEUM_DENSITY_VIOLATION = "MUSEUM_DENSITY_VIOLATION"
TOURISTINESS_MISMATCH = "TOURISTINESS_MISMATCH"

# Route / feasibility
TRAVEL_TIME_TOO_LONG = "TRAVEL_TIME_TOO_LONG"
ROUTE_BACKTRACKING = "ROUTE_BACKTRACKING"
UNREALISTIC_DURATION = "UNREALISTIC_DURATION"
INSUFFICIENT_MEAL_TIME = "INSUFFICIENT_MEAL_TIME"
LONG_WALK_BLOCK = "LONG_WALK_BLOCK"
PLACE_RESOLUTION_FAILED = "PLACE_RESOLUTION_FAILED"

# Memory
CONFLICT_WITH_USER_MEMORY = "CONFLICT_WITH_USER_MEMORY"
MISSED_STRONG_USER_PREFERENCE = "MISSED_STRONG_USER_PREFERENCE"
